version: '3.7'

services:
  dnsmasq:
    image: jpillora/dnsmasq
    container_name: dnsmasq
    deploy:
      resources:
        limits:
          memory: 256m
    ports:
      - "53:53/udp"
      - "5380:8080"
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    logging:
      options:
        max-size: 100m
    restart: on-failure