version: '3'

services:
  reverse-proxy:
    image: traefik:alpine
    ports:
      - "80:80"
      - "3000:3000"
      - "3001:3001"
      - "8080:8080"
      - "35729:35729"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
    restart: on-failure
